### ISSUE TITLE
Test about some Compound phases in Sm-Fe-B.

### ISSUE THREAD

**Issue by Hans540** [amkrajewski/MPDD-X#37]
We are happy to quickly add any structure-informed model which is a plug-and-play addition to our infrastructure, which will generally mean it either:
- Utilizes already implemented representation, feature set, or its subset. Please check below as appropriate:
    - [ ] My model uses [`KS2022`](https://pysipfenn.readthedocs.io/en/v0.15.0/source/pysipfenn.descriptorDefinitions.html) or its subset.
    - [ ] My model uses [`ALIGNN`](https://github.com/usnistgov/alignn/blob/main/alignn/models/alignn.py#L190) graph representation.
    - [ ] My model is a refitting or a variation of [`CHGNet`](https://github.com/CederGroupHub/chgnet/blob/main/chgnet/model/model.py#L33)
    - [ ] My model is available from a public citable source like Zenodo (preferred) or figshare.
    - [ ] My model can be fetched within 30s, corresponding to ~2GB on Zenodo or 250MB on figshare.
    - [ ] My model can run single-threaded in under 500ms / structure
    - [ ] My model can run single-threaded in under 5s / structure

- Is a lightweight tool, which can be quickly installed and run. Please check below as appropriate:
    - [ ] My model is well maintained and has been used in past research.
    - [ ] My model is actively tested at least weekly and has been well-maintained for at least 6 months.
    - [ ] My model is available from a public citable source like Zenodo (preferred) or figshare.
    - [ ] My model can be fetched within 30s, corresponding to ~2GB on Zenodo or 250MB on figshare.
    - [ ] My model can run single-threaded in under 500ms / structure
    - [ ] My model can run single-threaded in under 5s / structure
 
If it does not fall into the above categories, please dont get discouraged and still let us know! It will be much more work on our side, but we will probably be happy to work with you. To get started on that, please explain it in a few sentences.

**Comment by Hans540** [comment]
[Uploading Sm-Fe-B.zip…]()

**Comment by Hans540** [comment]
[Sm-Fe-B.zip](https://github.com/amkrajewski/MPDD-X/files/15321831/Sm-Fe-B.zip)

**Comment by amkrajewski** [comment]
Hi @Hans540 these seems to be an issue with your `CIF` files not being able to be read by neither `pymatgen` nor `jarvis`.

`pymatgen`:
```output
Importing structures...
  0%|          | 0/4 [00:00<?, ?it/s]/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymatgen/io/cif.py:213: UserWarning: Possible issue in CIF file at line: P42/mnm
  warnings.warn(f"Possible issue in CIF file at line: {issue}")
Traceback (most recent call last):
  File "/Users/runner/work/MPDD-X/MPDD-X/featurization/pysipfenn-minimal.py", line 12, in <module>
    c.runFromDirectory('structures', 'KS2022', 'serial')
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pysipfenn/core/pysipfenn.py", line 921, in runFromDirectory
    structList = [Structure.from_file(f'{directory}/{eif}') for eif in tqdm(self.inputFiles)]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pysipfenn/core/pysipfenn.py", line 921, in <listcomp>
    structList = [Structure.from_file(f'{directory}/{eif}') for eif in tqdm(self.inputFiles)]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymatgen/core/structure.py", line 2937, in from_file
    return cls.from_str(contents, fmt="cif", primitive=primitive, sort=sort, merge_tol=merge_tol, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymatgen/core/structure.py", line 2847, in from_str
    struct = parser.parse_structures(primitive=primitive)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymatgen/io/cif.py", line 1188, in parse_structures
    raise RuntimeError("remove the change of default primitive=True to False made on 2023-10-24")
RuntimeError: remove the change of default primitive=True to False made on 2023-10-24
```

`jarvis`:
```output
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jarvis/core/atoms.py", line 340, in from_cif
    lines = f.read().splitlines()
            ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 846: invalid continuation byte
```

**Comment by Hans540** [comment]
[Sm-Fe-B(1).zip](https://github.com/amkrajewski/MPDD-X/files/15323078/Sm-Fe-B.1.zip)
